# the ip of Data Construction Service
DCS_ip: '10.60.2.182'

# the port of Data Construction Service
DCS_port: '6078'

# the type of data save: 0-raw 1-hdf5
Data_save_type: '1'

# the path of hdf5 file
hdf5_path: "config/airspeed_data.hdf5"
